#!/usr/bin/env bash
# Display information about subdomains.
# Configures;
#  www-> 167389-lb-01 100.26.164.61
#  web-01-> 167389-web-01 -54.89.194.128
#  web-02-> 167389-web-02 -54.209.119.141

subdomains_all=("www" "lb-01" "web-01" "web-02")
runDig () {
    subdomain="$1"
    domain="$2"

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v
s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4
"\nrecord and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains_all[@]}"
    do
    runDig "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    runDig "$subdomain" "$domain"
fi
