#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.
#+++ it redirects to another page to "301 moved permanently"

sudo apt-get update
sudo apt-get install -y nginx


sudo sh -c 'echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;

     location /redirect_me {
         return 301 http://reuszed.com/;

     }

     root        /var/www/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default'

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
