#!/usr/bin/env bash
# It installs and configure HAproxy on my 1b-01 server.
#++ It is  configured to send traffic to web-01 and web-02
#++ It distributes requests using roundrobin algorithm.
#++ It is configured with hostnames :167389-web-01 and 167389-web-02.


apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*


echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg


printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
   log    global
   mode   http
   option httplog
   option dontlognull
   retries 3
   option redispatch
   timeout connect 5000
   timeout client  50000
   timeout server  50000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 167389-web-01 54.89.194.128:80 check
    server 167389-web-02 54.209.119.141:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
sudo systemctl restart haproxy.service

sudo systemctl enable haproxy.service
