#!/usr/bin/env bash
# It installs and configure HAproxy on my 1b-01 server.
#++ It is  configured to send traffic to web-01 and web-02
#++ It distributes requests using roundrobin algorithm.
#++ It is configured with hostnames :167389-web-01 and 167389-web-02.

sudo apt-get update
sudo apt-get install -y haproxy

sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo touch /etc/haproxy/haproxy.cfg
sudo chmod 666 /etc/haproxy/haproxy.cfg
echo "global
   log /dev/log   local0
   log /dev/log   local1 notice
   chroot /var/lib/haproxy
   stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
   stats timeout 30s
   user haproxy
   group haproxy
   daemon

defaults
   log    global
   mode   http
   option httplog
   option dontlognull
   retries 3
   timeout connect 5000
   timeout client  50000
   timeout server  50000

frontend www
   bind *:80
   default_backend webservers

backend webservers
   balance roundrobin
   server web-01 167389-web-01:80 check
   server web-02 167389-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo chmod 644 /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy.service

sudo systemctl enable haproxy.service
