#!/usr/bin/env bash
#+ Create a new configuration file for Nginx to listen on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
