#!/usr/bin/env bash
# Running has Nginx
pkill -f apache2
nginx_conf="/etc/nginx/nginx.conf"
user_directive="user nginx;"

if ! grep -q "$user_directive" "$nginx_conf"; then
  sed -i "1i $user_directive" "$nginx_conf"
fi

sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-enabled/default
nginx -s reload
